### ISSUE TITLE
Incompatible with prompt-toolkit 2

### ISSUE THREAD

**Issue by ChiChou** [frida/frida-tools#10]
prompt-toolkit has breaking change:
(like this: https://github.com/jupyter/jupyter_console/issues/158)

```
$ frida Finder
Traceback (most recent call last):
  File "/usr/local/bin/frida", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/frida_tools/repl.py", line 23, in main
    from prompt_toolkit.shortcuts import create_prompt_application, create_output, create_eventloop
ImportError: cannot import name 'create_prompt_application' from 'prompt_toolkit.shortcuts' (/usr/local/lib/python3.7/site-packages/prompt_toolkit/shortcuts/__init__.py)
```
For those who has encountered same problem, you can temporary downgrade by `pip3 install 'prompt-toolkit==1.0.15'`

**Comment by oleavr** [comment]
That's intentional if you look at `setup.py`:

```
prompt-toolkit >= 0.57, < 2.0.0
```

Due to lack of time I didn't get around to upgrading to the latest. PR welcome!
